### ISSUE TITLE
Question about the data and code.

### ISSUE THREAD

**Issue by BarryBA** [warden3344/unet#1]
I have download your code, but it can not work based on my dataset (RGB images).
I wonder to know what's your dataset, is it gray image?
The error reported is always on:
"error: OpenCV(3.4.1) /opt/conda/conda-bld/opencv-suite_1530789967746/work/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize"
Can you help me? thank you very much!

**Comment by TqDavid** [comment]
@BarryBA 您好，请问一下您该如何准备数据集呢

**Comment by TqDavid** [comment]
@BarryBA 您好，请问一下您该如何准备数据集呢
@Warden3344

**Comment by warden3344** [comment]
@BarryBA Sorry there is something wrong with my origin model,I have update the solver and model proto file, you my update by this  and have a try. the data type is not matter, RGB or GRAY is all right. may be your file path is not correct.

**Comment by warden3344** [comment]
@TqDavid 数据集按照提供的data那样准备就行，准备同名的标记图像，然后设置正确路径就行

**Comment by taotaoyuhust** [comment]
数据层里面写死了路径，好像只有train，没有用到val？

**Comment by warden3344** [comment]
是的，数据层请自己改写
