### ISSUE TITLE
Creating layer data ImportError: No module named mydatalayer

### ISSUE THREAD

**Issue by pele228** [warden3344/unet#2]
你好，按照文档运行时新加的层提示没有找到
I0428 11:08:53.128757 510520 layer_factory.hpp:77] Creating layer data
ImportError: No module named mydatalayer
请问这个层应加在什么位置?

**Comment by warden3344** [comment]
mydatalayer 就是路径下的mydatalayer.py，可以自己修改实现，再把mydatalayer.py所在目录添加到pythonpath里头就行
